print('Hello World')
my_name = input('Whats your name ')
print('Its good to meet you ' + my_name)
print('The length of you name is: ')
print(len(my_name))
print('What is your age? ')
my_age = input()
print('You will be ' + str(int(my_age) + 1) + ' in a year')
